version: '3.8'

services:
  database:
    image: mongo:latest
    volumes:
      - mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=houseDB
      # you can access to the db via "$ mongosh -u houseAdmin -p housePassAdmin"
      - MONGO_INITDB_ROOT_USERNAME=houseAdmin
      - MONGO_INITDB_ROOT_PASSWORD=housePassAdmin
    command: mongod --auth
    ports:
      - '27017-27019:27017-27019'


  server:
    container_name: housemate_backend
    build: ./backend
    environment:
      - MONGODB_URI=mongodb://database:27017/houseDB
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  mongodbdata:
    driver: local
